config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "subscriptions#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user

  validates :card_expiry, comparison: { greater_than_or_equal_to: :today}
  validates :cvc, comparison: { other_than: '999' }
  private

  def today
    Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :subscription
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]

  # GET /subscriptions or /subscriptions.json
  def index
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
    @user = current_user
    @subscription = @user&.subscription
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @user = current_user
    @subscription = Subscription.new(subscription_params)
    @subscription.user = @user

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Subscription was successfully cancelled." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      if params[:id]
        @subscription = Subscription.find(params[:id])
      else
        @subscription = nil
      end
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:card_number, :card_expiry, :cvc)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/home/index.html.erb
<h1>Landing Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IwinDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary navbar bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">iWin</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item text-light">
              <%= "#{current_user.name}  " %>
            </li>
            <li>
              "  "
            </li>
            <li class="nav-item">
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, type:"button", class:"btn btn-light btn-sm" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= button_to "Sign in", new_user_session_path, type:"button", class:"btn btn-light btn-sm"  %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>


  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :card_number, style: "display: block" %>
    <%= form.text_field :card_number, :required => true, :minlength => 16, :maxlength => 16, :placeholder => "16-digits" %>
  </div>

  <div>
    <%= form.label :card_expiry, style: "display: block" %>
    <%= form.date_field :card_expiry, :required => true %>
  </div>

  <div>
    <%= form.label :cvc, style: "display: block" %>
    <%= form.text_field :cvc, :required => true, :minlength => 3, :maxlength => 3, :placeholder => "3-digits" %>
  </div>

  <div>
    <%= form.hidden_field :user, value: current_user.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
  <p>
    <strong>Card number:</strong>
    <%= '************' + subscription.card_number.last(4) %>
  </p>

  <p>
    <strong>Card expiry:</strong>
    <%= subscription.card_expiry %>
  </p>

  <p>
    <strong>Cvc:</strong>
    <%= "***" %>
  </p>

</div>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Show this subscription", @subscription %> |
  <%= link_to "Back home", root_path %>
</div>

app/views/subscriptions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subscriptions</h1>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Back to home", root_path %>
</div>

app/views/subscriptions/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subscription Status</h1>

<% if user_signed_in? %>
  <% if @subscription %>
    <p> Subscription is active</p>
    <%= render @subscription %>
    <div>
      <%= link_to "Update this subscription", edit_subscription_path(@subscription) %>

      <%= button_to "Cancel this subscription", @subscription, method: :delete %>
    </div>
  <% else %>
    <p> No active subscription</p>
    <%= link_to "New subscription", new_subscription_path %>
  <% end %>
<% else %>
  <p> Sign in to see subscriptions</p>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>